# Generated by Django 3.2.15 on 2022-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('page_name', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=10)),
                ('git_url', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=30)),
            ],
        ),
    ]
