# Generated by Django 3.2.15 on 2022-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
