# Generated by Django 3.2.15 on 2022-09-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_instance_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='node',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='project_name',
        ),
    ]
